// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServerStatus_GetOnlineClient_FullMethodName = "/grpc.ServerStatus/GetOnlineClient"
)

// ServerStatusClient is the client API for ServerStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerStatusClient interface {
	GetOnlineClient(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OnlineClient, error)
}

type serverStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewServerStatusClient(cc grpc.ClientConnInterface) ServerStatusClient {
	return &serverStatusClient{cc}
}

func (c *serverStatusClient) GetOnlineClient(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OnlineClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineClient)
	err := c.cc.Invoke(ctx, ServerStatus_GetOnlineClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerStatusServer is the server API for ServerStatus service.
// All implementations must embed UnimplementedServerStatusServer
// for forward compatibility.
type ServerStatusServer interface {
	GetOnlineClient(context.Context, *Empty) (*OnlineClient, error)
	mustEmbedUnimplementedServerStatusServer()
}

// UnimplementedServerStatusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerStatusServer struct{}

func (UnimplementedServerStatusServer) GetOnlineClient(context.Context, *Empty) (*OnlineClient, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnlineClient not implemented")
}
func (UnimplementedServerStatusServer) mustEmbedUnimplementedServerStatusServer() {}
func (UnimplementedServerStatusServer) testEmbeddedByValue()                      {}

// UnsafeServerStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interfaces is not recommended, as added methods to ServerStatusServer will
// result in compilation errors.
type UnsafeServerStatusServer interface {
	mustEmbedUnimplementedServerStatusServer()
}

func RegisterServerStatusServer(s grpc.ServiceRegistrar, srv ServerStatusServer) {
	// If the following call pancis, it indicates UnimplementedServerStatusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServerStatus_ServiceDesc, srv)
}

func _ServerStatus_GetOnlineClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerStatusServer).GetOnlineClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerStatus_GetOnlineClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerStatusServer).GetOnlineClient(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerStatus_ServiceDesc is the grpc.ServiceDesc for ServerStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ServerStatus",
	HandlerType: (*ServerStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOnlineClient",
			Handler:    _ServerStatus_GetOnlineClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
