// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: service.proto

package grpc_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type OnlinePilot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Callsign      string                 `protobuf:"bytes,1,opt,name=callsign,proto3" json:"callsign,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Cid           int32                  `protobuf:"varint,4,opt,name=cid,proto3" json:"cid,omitempty"`
	RealName      string                 `protobuf:"bytes,5,opt,name=realName,proto3" json:"realName,omitempty"`
	Lat           float32                `protobuf:"fixed32,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,7,opt,name=lon,proto3" json:"lon,omitempty"`
	Transponder   int32                  `protobuf:"varint,8,opt,name=transponder,proto3" json:"transponder,omitempty"`
	Altitude      int32                  `protobuf:"varint,9,opt,name=altitude,proto3" json:"altitude,omitempty"`
	GroundSpeed   int32                  `protobuf:"varint,10,opt,name=groundSpeed,proto3" json:"groundSpeed,omitempty"`
	OnlineTime    int64                  `protobuf:"varint,11,opt,name=onlineTime,proto3" json:"onlineTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePilot) Reset() {
	*x = OnlinePilot{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePilot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePilot) ProtoMessage() {}

func (x *OnlinePilot) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePilot.ProtoReflect.Descriptor instead.
func (*OnlinePilot) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *OnlinePilot) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *OnlinePilot) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OnlinePilot) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OnlinePilot) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *OnlinePilot) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *OnlinePilot) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *OnlinePilot) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *OnlinePilot) GetTransponder() int32 {
	if x != nil {
		return x.Transponder
	}
	return 0
}

func (x *OnlinePilot) GetAltitude() int32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *OnlinePilot) GetGroundSpeed() int32 {
	if x != nil {
		return x.GroundSpeed
	}
	return 0
}

func (x *OnlinePilot) GetOnlineTime() int64 {
	if x != nil {
		return x.OnlineTime
	}
	return 0
}

type OnlineAtc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Callsign      string                 `protobuf:"bytes,1,opt,name=callsign,proto3" json:"callsign,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Cid           int32                  `protobuf:"varint,4,opt,name=cid,proto3" json:"cid,omitempty"`
	RealName      string                 `protobuf:"bytes,5,opt,name=realName,proto3" json:"realName,omitempty"`
	Lat           float32                `protobuf:"fixed32,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,7,opt,name=lon,proto3" json:"lon,omitempty"`
	Rating        int32                  `protobuf:"varint,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Facility      string                 `protobuf:"bytes,9,opt,name=facility,proto3" json:"facility,omitempty"`
	Frequency     int32                  `protobuf:"varint,10,opt,name=frequency,proto3" json:"frequency,omitempty"`
	AtcInfo       []string               `protobuf:"bytes,11,rep,name=atcInfo,proto3" json:"atcInfo,omitempty"`
	OnlineTime    int64                  `protobuf:"varint,12,opt,name=onlineTime,proto3" json:"onlineTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineAtc) Reset() {
	*x = OnlineAtc{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineAtc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineAtc) ProtoMessage() {}

func (x *OnlineAtc) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineAtc.ProtoReflect.Descriptor instead.
func (*OnlineAtc) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *OnlineAtc) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *OnlineAtc) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OnlineAtc) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OnlineAtc) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *OnlineAtc) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *OnlineAtc) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *OnlineAtc) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *OnlineAtc) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *OnlineAtc) GetFacility() string {
	if x != nil {
		return x.Facility
	}
	return ""
}

func (x *OnlineAtc) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *OnlineAtc) GetAtcInfo() []string {
	if x != nil {
		return x.AtcInfo
	}
	return nil
}

func (x *OnlineAtc) GetOnlineTime() int64 {
	if x != nil {
		return x.OnlineTime
	}
	return 0
}

type OnlineClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalOnline   int32                  `protobuf:"varint,1,opt,name=totalOnline,proto3" json:"totalOnline,omitempty"`
	AtcOnline     int32                  `protobuf:"varint,2,opt,name=atcOnline,proto3" json:"atcOnline,omitempty"`
	PilotOnline   int32                  `protobuf:"varint,3,opt,name=pilotOnline,proto3" json:"pilotOnline,omitempty"`
	OnlineAtc     []*OnlineAtc           `protobuf:"bytes,4,rep,name=onlineAtc,proto3" json:"onlineAtc,omitempty"`
	OnlinePilot   []*OnlinePilot         `protobuf:"bytes,5,rep,name=onlinePilot,proto3" json:"onlinePilot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineClient) Reset() {
	*x = OnlineClient{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineClient) ProtoMessage() {}

func (x *OnlineClient) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineClient.ProtoReflect.Descriptor instead.
func (*OnlineClient) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *OnlineClient) GetTotalOnline() int32 {
	if x != nil {
		return x.TotalOnline
	}
	return 0
}

func (x *OnlineClient) GetAtcOnline() int32 {
	if x != nil {
		return x.AtcOnline
	}
	return 0
}

func (x *OnlineClient) GetPilotOnline() int32 {
	if x != nil {
		return x.PilotOnline
	}
	return 0
}

func (x *OnlineClient) GetOnlineAtc() []*OnlineAtc {
	if x != nil {
		return x.OnlineAtc
	}
	return nil
}

func (x *OnlineClient) GetOnlinePilot() []*OnlinePilot {
	if x != nil {
		return x.OnlinePilot
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x04grpc\"\a\n" +
	"\x05Empty\"\xad\x02\n" +
	"\vOnlinePilot\x12\x1a\n" +
	"\bcallsign\x18\x01 \x01(\tR\bcallsign\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03cid\x18\x04 \x01(\x05R\x03cid\x12\x1a\n" +
	"\brealName\x18\x05 \x01(\tR\brealName\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\a \x01(\x02R\x03lon\x12 \n" +
	"\vtransponder\x18\b \x01(\x05R\vtransponder\x12\x1a\n" +
	"\baltitude\x18\t \x01(\x05R\baltitude\x12 \n" +
	"\vgroundSpeed\x18\n" +
	" \x01(\x05R\vgroundSpeed\x12\x1e\n" +
	"\n" +
	"onlineTime\x18\v \x01(\x03R\n" +
	"onlineTime\"\xb7\x02\n" +
	"\tOnlineAtc\x12\x1a\n" +
	"\bcallsign\x18\x01 \x01(\tR\bcallsign\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03cid\x18\x04 \x01(\x05R\x03cid\x12\x1a\n" +
	"\brealName\x18\x05 \x01(\tR\brealName\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\a \x01(\x02R\x03lon\x12\x16\n" +
	"\x06rating\x18\b \x01(\x05R\x06rating\x12\x1a\n" +
	"\bfacility\x18\t \x01(\tR\bfacility\x12\x1c\n" +
	"\tfrequency\x18\n" +
	" \x01(\x05R\tfrequency\x12\x18\n" +
	"\aatcInfo\x18\v \x03(\tR\aatcInfo\x12\x1e\n" +
	"\n" +
	"onlineTime\x18\f \x01(\x03R\n" +
	"onlineTime\"\xd4\x01\n" +
	"\fOnlineClient\x12 \n" +
	"\vtotalOnline\x18\x01 \x01(\x05R\vtotalOnline\x12\x1c\n" +
	"\tatcOnline\x18\x02 \x01(\x05R\tatcOnline\x12 \n" +
	"\vpilotOnline\x18\x03 \x01(\x05R\vpilotOnline\x12-\n" +
	"\tonlineAtc\x18\x04 \x03(\v2\x0f.grpc_server.OnlineAtcR\tonlineAtc\x123\n" +
	"\vonlinePilot\x18\x05 \x03(\v2\x11.grpc_server.OnlinePilotR\vonlinePilot2B\n" +
	"\fServerStatus\x122\n" +
	"\x0fGetOnlineClient\x12\v.grpc_server.Empty\x1a\x12.grpc_server.OnlineClientB\x04Z\x02./b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_proto_goTypes = []any{
	(*Empty)(nil),        // 0: grpc_server.Empty
	(*OnlinePilot)(nil),  // 1: grpc_server.OnlinePilot
	(*OnlineAtc)(nil),    // 2: grpc_server.OnlineAtc
	(*OnlineClient)(nil), // 3: grpc_server.OnlineClient
}
var file_service_proto_depIdxs = []int32{
	2, // 0: grpc_server.OnlineClient.onlineAtc:type_name -> grpc_server.OnlineAtc
	1, // 1: grpc_server.OnlineClient.onlinePilot:type_name -> grpc_server.OnlinePilot
	0, // 2: grpc_server.ServerStatus.GetOnlineClient:input_type -> grpc_server.Empty
	3, // 3: grpc_server.ServerStatus.GetOnlineClient:output_type -> grpc_server.OnlineClient
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
